// default package
// Generated 22 ene 2026, 16:35:20 by Hibernate Tools 6.5.1.Final
package com.gf.sede.entities;

import java.util.HashSet;
import java.util.Set;

/**
 * Entidades generated by hbm2java
 */
public class Entidades implements java.io.Serializable {

	private String nombre;
	private Set registroses = new HashSet(0);

	public Entidades() {
	}

	public Entidades(String nombre) {
		this.nombre = nombre;
	}

	public Entidades(String nombre, Set registroses) {
		this.nombre = nombre;
		this.registroses = registroses;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getRegistroses() {
		return this.registroses;
	}

	public void setRegistroses(Set registroses) {
		this.registroses = registroses;
	}

}
