// default package
// Generated 22 ene 2026, 16:35:20 by Hibernate Tools 6.5.1.Final
package com.gf.sede.entities;

import java.sql.Date;

/**
 * Registros generated by hbm2java
 */
public class Registros implements java.io.Serializable {

	private String numeroRegistro;
	private Entidades entidades;
	private String dni;
	private String nombre;
	private String apellidos;
	private String tramite;
	private Date fecha;

	public Registros() {
	}

	public Registros(String numeroRegistro, Entidades entidades, String dni, String nombre, String apellidos,
			String tramite, Date fecha) {
		this.numeroRegistro = numeroRegistro;
		this.entidades = entidades;
		this.dni = dni;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.tramite = tramite;
		this.fecha = fecha;
	}

	public String getNumeroRegistro() {
		return this.numeroRegistro;
	}

	public void setNumeroRegistro(String numeroRegistro) {
		this.numeroRegistro = numeroRegistro;
	}

	public Entidades getEntidades() {
		return this.entidades;
	}

	public void setEntidades(Entidades entidades) {
		this.entidades = entidades;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getTramite() {
		return this.tramite;
	}

	public void setTramite(String tramite) {
		this.tramite = tramite;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
